services:
#  server:
#    build:
#      context: .
#      dockerfile: dockerfile
#    volumes:
#      - ./src:/app/src
#    env_file:
#      - ./.env
#    environment:
#      - DATABASE_URL=mongodb://mongodb:27017/martcart
#    depends_on:
#      - mongodb
#    ports:
#      - 5000:5000
#    extra_hosts:
#      - host.docker.internal:host-gateway

  mongodb:
    image: mongo
    volumes:
      - ./migrations/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      - MONGO_INITDB_DATABASE=martcart
    ports:
      - 27017:27017